### ISSUE TITLE
[Feature] Missing Comment Rule

### ISSUE THREAD

**Issue by MarcoEidinger** [dral3x/StringsLint#15]
Hi Alessandro,

awesome project!! ❤️ 

I am working in a large development team and we want to enforce that developers will add a comment to each localizable string. This will ensure that translators will have more contextual information to provide a good translation. Hence I was thinking about a new "Missing Comment Rule".

I am currently implementing this feature in my fork and I would open a PR if you think that this is useful in general.

Cheers,
Marco

**Comment by dral3x** [comment]
Hi @MarcoEidinger !
Thanks! I'm glad you like this project!

"Missing Comment" is a need that StringLint could check for sure. 
I would love to get a PR and merge this feature here! Looking forward to it!

If you need help, let me know.
Alessandro

**Comment by MarcoEidinger** [comment]
Hi @dral3x , PR is ready for your review.
