### ISSUE TITLE
Custom rules by regex

### ISSUE THREAD

**Issue by bigearsenal** [dral3x/StringsLint#21]
Hi there, I couldn't find a way to simply create new rules by regex like SwiftLint. How can I archive that?

**Comment by dral3x** [comment]
Hi @bigearsenal,

StringsLint supports only hardcoded rules (as you can see [here](https://github.com/dral3x/StringsLint/tree/master/Sources/StringsLintFramework/Rules/Lint)). 

To archive what you want, you need to create a new one (in swift like the others) that picks from the configuration file any regex you declare there and verify it across all localized strings.

**Comment by dral3x** [comment]
@bigearsenal The just released version of stringslint support custom regex for string detection.
https://github.com/dral3x/StringsLint/releases/tag/0.1.6

Give it a go if you're still interested! Thank you
