### ISSUE TITLE
Include an x86_64 release

### ISSUE THREAD

**Issue by TylerJang27** [dral3x/StringsLint#28]
The `0.1.1` portable release included an x86_64 executable, which was available on both M1 (via Rosetta) and Intel CPUs. Since then, arm64 executables have been uploaded, breaking compatibility with the Intel chips. Could a new (or replacement) portable release be uploaded for `0.1.2` and above? Thanks!

**Comment by dral3x** [comment]
Hello @TylerJang27 
thanks for pointing that out.

I had to manually build stringslint from my machine, making the build arm64, but it was not intentional.
I'll check how to rebuild it using both archs, or at least x86_64.

**Comment by dral3x** [comment]
@TylerJang27 please try with version 0.1.3. I just rebuild it with both archs in place.

**Comment by TylerJang27** [comment]
Works perfectly on both archs. Thanks!
