### ISSUE TITLE
SwiftUI - Disable implicit detection

### ISSUE THREAD

**Issue by AnthoPakPak** [dral3x/StringsLint#34]
Thanks a lot for the lib!

I'd like to prevent it to detect SwiftUI implicitely. For example `Text("abc")` and `Button("abc")` are detected. Is there a way to prevent this behavior? I only want to detect them when it is explicit.

I've researched in the lib but can't find if there's a way to do this :)

**Comment by dral3x** [comment]
Hey @AnthoPakPak, thank you for using the lib!

At the moment there's no way to disable those implicit detections. 

You can open a PR that makes those implicit checks being turned off via configuration (`SwiftParserConfiguration`). I'm totally interested in integrating this feature!

**Comment by dral3x** [comment]
@AnthoPakPak I've implemented this feature in the latest version of stringslint 0.1.7

Check it out!
